RegistroDeVentas/Models/ErrorViewModel.cs
using System;

namespace RegistroDeVentas.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RegistroDeVentas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RegistroDeVentas.Models;

namespace RegistroDeVentas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

RegistroDeVentas/Controllers/PresentacionWeb3Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace RegistroDeVentas.Controllers
{
    public class PresentacionWeb3Controller : Controller
    {
        // GET
        public IActionResult Bienvenidxs()
        {
            return View();
        }
    }
}

RegistroDeVentas/Controllers/VentasController.cs
using System.Collections.Generic;
using CapaNegocio.Entidades;
using CapaNegocio.Servicios;
using Microsoft.AspNetCore.Mvc;

namespace RegistroDeVentas.Controllers
{
    public class VentasController : Controller
    {
        private VentasService service;

        public VentasController()
        {
            service = new VentasService();
        }
        
        public IActionResult RegistrarVenta()
        {
            return View();
        }

        public IActionResult Resultados()
        {
            List<Venta> ListaDeVentas = service.ListarTodasLasVentas();
            ViewBag.ListaDeventas = ListaDeVentas;
            return View();
        }

        [HttpPost]
        public IActionResult RegistrarVenta(Venta venta)
        {
            int CantidadVendida = venta.CantidadVendida;
            int PrecioUnitario = venta.PrecioUnitario;
            int TotalSinIva = CantidadVendida * PrecioUnitario;
            venta.TotalVenta = TotalSinIva * 1.21;
            venta.IDVenta = service.ObtenerIDVenta();
            service.AgregarVenta(venta);
            return RedirectToAction(nameof(Resultados));
        }
    }
}

RegistroDeVentas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RegistroDeVentas/Views/PresentacionWeb3/Bienvenidxs.cshtml
@{
    ViewData["Title"] = "Bienvenidxs";
}

<h1>Bienvenidxs al sitio de evaluación Web 3</h1>

<hr/>

<div class="mt-3">
    <ul>
        <li>
            <a asp-controller="Ventas" asp-action="RegistrarVenta">Registrar Venta</a>
        </li>
        <li>
            <a asp-controller="Ventas" asp-action="Resultados">Ver Resultados</a>
        </li>
    </ul>
</div>

RegistroDeVentas/Views/Shared/_Datos.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RegistroDeVentas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<div class="container">
    <main role="main" class="pb-3 mt-5">
        @RenderBody()
    </main>
</div>

<footer>
    <hr/>

    <div class="text-center">
        <p>Matias Rubén Alarcón</p>
        <p>35909713</p>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RegistroDeVentas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RegistroDeVentas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RegistroDeVentas</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - RegistroDeVentas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RegistroDeVentas/Views/Ventas/RegistrarVenta.cshtml
@model CapaNegocio.Entidades.Venta

@{
    ViewData["title"] = "Registrar Venta";
}

<h1>Registrar Venta</h1>

<h2>Venta</h2>
<form asp-action="RegistrarVenta" asp-controller="Ventas" method="POST">
    <div class="form-group">
        <label asp-for="Cliente">Cliente:</label>
        <input asp-for="Cliente" type="text" class="form-control" placeholder="Ingrese nombre del cliente"/>
        <span asp-validation-for="Cliente" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CantidadVendida">Cantidad Vendida:</label>
        <input asp-for="CantidadVendida" type="number" class="form-control" placeholder="0"/>
        <span asp-validation-for="CantidadVendida" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PrecioUnitario">Precio Unitario:</label>
        $ <input asp-for="PrecioUnitario" type="number" class="form-control" placeholder="0"/>
        <span asp-validation-for="PrecioUnitario" class="text-danger"></span>
    </div>
    <button class="btn btn-success">Registrar Venta</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}

RegistroDeVentas/Views/Ventas/Resultados.cshtml
@{
    ViewData["title"] = "Ver Resultados";
}


<h1>Ver Resultados</h1>

@if (ViewBag.ListaDeVentas.Count > 0)
{
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#IDVenta</th>
          <th scope="col">Cliente</th>
          <th scope="col">Cantidad Vendida</th>
          <th scope="col">Precio Unitario ($)</th>
          <th scope="col">Total Venta</th>
        </tr>
      </thead>
      <tbody>
      @foreach (var venta in ViewBag.ListaDeVentas)
          {
             <tr>
                 <th scope="row">@venta.IDVenta</th>
                 <td>@venta.Cliente</td>
                 <td>@venta.CantidadVendida</td>
                 <td>@venta.PrecioUnitario</td>
                 <td>@venta.TotalVenta</td>
                 </tr>
          }
      </tbody>
    </table>
}
else
{
    <h2>No hay Ventas</h2>
}

<a asp-controller="Ventas" asp-action="RegistrarVenta">Registrar Venta</a>